config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :path => '', 
               :path_names=>{:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
               :controllers=>{:registrations => 'registrations', :companies => 'create'}
  root 'pages#home'
  
  
  resources :users, only: [:show]
  resources :companies
  
  resources :photos
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  
  validates :social_reason, presence: true, length: {maximum: 100}
  validates :email_company, presence: true, length: {maximum: 100}
  validates :address_company, presence: true, length: {maximum: 100}
  #validates :tel_company, presence: true, length: {maximum: 20}
  validates :legal_status, presence: true, length: {maximum: 50}
  #validates :num_tva, presence: true, length: {maximum: 50}
  #validates :rcs, presence: true, length: {maximum: 50}
  #validates :ape_code, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 800}
  validates :offer, presence: true, length: {maximum: 800}
  validates :creation_date, presence: true, length: {maximum: 10}
  validates :staff, numericality: {only_integer: true, greather_than: 1}
  #validates :turnover, numericality: {only_integer: true, greather_than: 1000}
  validates :website, presence: true, length: {maximum: 100}
 
#Google maps     
  geocoded_by :address_company
  after_validation :geocode, if: :address_company_changed?
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :company
  
  
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :company
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
         
         validates :first_name, presence:true, length: {maximum: 50}
         validates :last_name, presence:true, length: {maximum: 50}
         validates :social_reason, presence:true, length: {maximum: 100}
         validates :profil, presence:true, length: {maximum: 100}
         validates :siret, presence:true, length: {maximum: 20}
         validates :tel, presence:true, length: {maximum: 20}
         validates :rubric, presence:true, length: {maximum: 50}
         validates :address, presence:true, length: {maximum: 150}
         validates :city, presence:true, length: {maximum: 60}

#Google maps      
#    geocoded_by :address_company
#    after_validation :geocode, if: :address_changed?  
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :social_reason, :profil, :siret, :tel, :rubric, :address, :city, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :social_reason, :profil, :siret, :tel, :rubric, :address, :city, :avatar])
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    
before_action :set_company, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show]
#before_action :require_same_user, except: [:edit, :update]
    def index
        @company = Company.all
    end
    def new
       @company = Company.new
    end

    def create
            #@company = current_user.company.new
            @company = Company.new(company_params)
                if @company.save
                    if params[:images]
                        params[:images].each do |i|
                            @company.photos.create(image: i)
                        end
                    end
                    @photos = @company.photos
                    redirect_to edit_company_path(@company), notice:"Votre entreprise a été ajoutée avec succès"
                else
                    render :new
                end
    end
    
    def show
       @photos = @company.photos
       @user = User.find(params[:id]) 
    end
    def edit
        @photos = @company.photos
    end
    def update
       if @company.update(company_params)
            if params[:images]
            params[:images].each do |i|
                    @company.photos.create(image: i)
                end
            end
                    @photos = @company.photos
              redirect_to edit_company_path(@company), notice:"Modification enregistrée..."
       else
           render :edit
       end
    end
    
private
 
    def set_company
         @company = Company.find(params[:id])
    end
        
    def company_params
        params.require(:company).permit(:social_reason, :email_company, :address_company, :legal_status,
                                        :num_tva, :description, :offer, :product, :creation_date, :website,
                                        :staff, :turnover, :active)
    end
    
   # def require_same_user
    #   if current_user.id != @company.user_id
     #      flash[:danger] = "Vous n'avez pas le droit de modifier cette page"
      #     redirect_to root_path
       #end
    #end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    
    def destroy
        @photo = Photo.find(params[:id])
        company = @photo.company
        
        @photo.destroy
        
        @photos = Photo.where(company_id: company.id)
        
        respond_to :js
        
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 
 protected
 
 def update_resource(resource, params)
 
     resource.update_without_password(params)
 
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def show 
      @user = User.find(params[:id])
      @company = Company.find(params[:id])
   end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def avatar_url(user)
        if user.avatar.present?
            user.avatar.url
        else
            'default_image.png'
        end
    end
end

app/views/companies/_form.html.erb
    <div class="panel panel-default">
        <div class="panel-heading">
            Votre mini-site web
        </div>
        <div class="panel-body">
            <div class="container">
                
                <%= form_for @company, html: {multipart: true} do |f| %>
                    <%= render 'shared/errors' %>
                        <div class="row"> 
                            <div class="form-group">
                                <%= f.label :social_reason %><br/>
                                <%= f.text_field :social_reason, class: "form-control", placeholder: "Nom de ma super entreprise" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :email_company %><br/>
                                <%= f.text_field :email_company, class: "form-control", placeholder: "Email affiché sur votre mini-site" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :address_company %><br/>
                                <%= f.text_field :address_company, class: "form-control", placeholder: "Adresse de votre entreprise" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :legal_status %><br/>
                                <%= f.text_field :legal_status, class: "form-control", placeholder: "Statut légal de votre entreprise" %>
                            </div>
                        </div>
                        <!-- <div class="row">
                                <div class="form-group">
                                <%= f.label :rcs %><br/>
                                <%= f.text_field :rcs, class: "form-control", placeholder: "Code RCS (non obligatoire)" %>
                            </div> 
                        </div> !-->
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :description %><br/>
                                <%= f.text_area :description, rows: 5,  class: "form-control", placeholder: "Faites une description de votre entreprise (800 caractères)" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :offer %><br/>
                                <%= f.text_area :offer, rows: 5,  class: "form-control", placeholder: "Décrivez les produits, services ... que vous proposez (800 caractères)" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :creation_date %><br/>
                                <%= f.text_field :creation_date, class: "form-control", placeholder: "Date de création de votre entreprise (année)" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :staff %><br/>
                                <%= f.text_field :staff, class: "form-control", placeholder: "Effectif de votre entreprise" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :turnover %><br/>
                                <%= f.text_field :turnover, class: "form-control", placeholder: "Chiffre d'affaire de l'année précédente (non-obligatoire)" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <%= f.label :website %><br/>
                                <%= f.text_field :website, class: "form-control", placeholder: "Adresse de votre site web : www.monsite.fr" %>
                            </div>
                        </div>
                        <div class="row">
                        <div class="form-group">
                            <%= f.check_box :active %> Voulez-vous que votre annonce soit visible sur vizioo.com ?
                        </div>
                    </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <span class="btn btn-default btn-file">
                                        <i class="fa fa-cloud-upload fa-lg"> </i> Télécharger vos photos !
                                        <%= file_field_tag "images[]", type: :file, multiple: true %>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div id="photos"><%= render 'photos/list' %></div>
                        <br>
                        <div class="actions">
                        <%= f.submit "Je valide mon annonce", class: "btn btn-primary"%>
                    </div>
                <% end %>
            </div>
        </div>
    </div>

app/views/companies/create.html.erb
<%= render 'form' %>

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/index.html.erb
    <div class="row">
          <div class="col-md-3">
                <ul class="sidebar-list">
                       <li class="sidebar-item"><%= link_to "Mon entreprise", companies_path, class: "sidebar-link active" %></li>
                </ul>
           </div>
           <div class="col-md-9">
                <div class="panel panel-default">
                     <div class="panel-heading">Mon entreprise
                     </div>
                    <div class="panel-body">
                          <% @company.each do |company| %>
                             <div class="row">
                                     <div class="col-md-2">
                                          <%= image_tag company.photos[0].image.url(:thumb) if company.photos.length > 0 %> 
                                     </div>                              
                                     <div class="col-md-7">
                                            <h4><%= company.social_reason %></h4>
                                     </div>
                                     <div class="col-md-3 right">
                                         <%= link_to "Mettre à jour", edit_company_path(company), class: "btn btn-primary" %>
                                     </div>
                            </div>
                       <% end %>
                   </div>
               </div>
         </div>
     </div>

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        
        <!-- Photo principale de l'annonce -->
        <div class="row">
            <div class="col-md-12">
                <%= image_tag @photos[0].image.url(), class:"img-responsive" if @photos.length > 0 %>
            </div>
        </div>
        
        <br>
        
        <!-- Information principales -->
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3 text center">
                        <%= image_tag avatar_url(current_user), class:"img-circle avatar-large" %>
                        <br>
                        <h3><%= @company.social_reason %></h3><br>
                        <%= @user.rubric %><br>
                        <%= @company.address_company %><br>
                        <%= @user.tel %><br>
                        <div class="row text-center row-space-1">
                            <h1>LA</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>

app/views/layouts/_navigation.html.erb
 <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
              <%= link_to image_tag('logo-vizioo-u101.png'), root_path, {:class=>"navbar-brand"} %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %> 
              
              <li><%= link_to 'Inscription', new_user_registration_path%></li>
              <li><%= link_to 'Connexion', new_user_session_path %></li>
              
        <% else %>
        
              <li>
                <%= link_to new_company_path do %><i class="fa fa-id-card-o fa-lg"></i> Créer votre mini-site ICI
                <% end %>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %>  <%= current_user.first_name %> <%= current_user.last_name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><%= link_to 'Mon entreprise', companies_path %></li>
                <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion',  destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VZ1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
<meta name="viewport" content="width=device-width, initial-scale=1">
<br>
<br>
<br>
<%= render 'layouts/navigation' %>



<%= render 'shared/message' %>



<div class="container"><%= yield %></div>
</body>
</html>

app/views/pages/home.html.erb
<h1></h1>

<div class="row">
    <div class="col-md-4">
        <div class="vignette">
            <div class="header">
                
                <h2>Camping de la mer</h2>
                <span class="adress">Camping Bretagne</span>
                <span class="adress">29630 PLOUGASNOU</span>
                <span class="tel">Tél. : 02 98 72 37 06</sapn>
            </div>
            <div class="vignette-content">
                <div class="description">
                    Le camping de la mer se situe sur la Pointe de Primel sur la commune de Plougasnou. Camping municipal 2 étoiles tout confort.
                </div>
                <div class="leftColumn">
                    <div class="caroussel"></div>            
                </div>
                <div class="rightColum"></div>
            </div>
            <i class="material-icons">code</i>
        </div>
    </div>
</div>
<br>
<br>
<hr>
<%= link_to 'Inscription', new_user_registration_path %> 
<%= link_to 'Identification', new_user_session_path %>
<%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %>

app/views/photos/_list.html.erb
<% if @photos %>
    <div class="row">
        <% @photos.each do |photo| %>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading preview">
                    <%= image_tag photo.image.url() %>
                </div>
                <div class="panel-body">
                    <span class="pull-right">
                        <%= link_to photo, remote: true, method: :delete, data: {confirm: "Attention, vous allez supprimer cette photo"} do %>
                            <i class="fa fa-times fa-lg"></i>
                        <% end %>
                    </span>
                </div>
            </div>
        </div>
        <% end %>
    </div>

<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
 
 <script type="text/javascript">
 
     <% resource.errors.full_messages.each do |msg| %>
 
               toastr.error('<%= msg %>')
 
     <% end %>
 
 </script>
 
<% end %>

app/views/shared/_errors.html.erb
<% unless @company.errors.empty? %>
    <script type="text/javascript">
     <% @company.errors.full_messages.each do |msg| %>
         toastr.error('<%= msg %>')
     <% end %>
    </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
 
       <script type="text/javascript">
 
       <% flash.each do |f| %>
 
        <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
 
         toastr['<%= type %>']('<%= f[1] %>')
 
       <% end %>
 
       </script>
 
 <% end %>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3 text-center">
        <%= image_tag avatar_url(@user), class:"avatar-full" %>
            <div class="panel panel-default">
                <div class="panel-heading">Mon entreprise</div>
                    <div class="panel-body">
                        Email : <%= @user.email %><br>
                        Numéro de téléphone : <%= @user.tel %><br>
                        Adresse : <%= @user.address %><br>
                        Ville : <%= @user.city %><br>
                        Numéro SIRET : <%= @user.siret %><br>
                        Catégorie : <%= @user.rubric %><br>
                    </div>
                </div>
        <div class="panel panel-default">
            <div class="panel-heading">Mes informations perso</div>
                <div class="panel-body">
                    Email : <%= @user.email %><br>
                    Prénom : <%= @user.first_name %><br>
                    Nom :<%= @user.last_name %><br>
                    Adresse: <%= @user.address %><br>
                    Ville: <%= @user.city %><br>
                    Poste occupé : <%= @user.tel %><br>
                </div>
            </div>


        <div class="panel panel-default">
            <div class="panel-heading">Qui sommes-nous ?</div>
                <div class="panel-body">
                    <%= @company.description %>
                </div>  
        </div>        
        <div class="panel panel-default">
            <div class="panel-heading">Nos services</div>
                <div class="panel-body">
                    <%= @company.offer %>
                </div>  
        </div>        
    </div>
    
    <!-- Google Maps -->
    <div class="row">
        <div class="col-md-12">
            <div id="map"></div>
            
            <style>
               #map {
                height: 400px;
                width: 100%;
               }
            </style>
            
            
            <script>
              function initMap() {
                var uluru = {lat: <%= @company.latitude %>, lng: <%= @company.longitude %>};
                var map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 15,
                  center: uluru
                });
                var marker = new google.maps.Marker({
                  position: uluru,
                  map: map
                });
              }
            </script>
            <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyANHJHWCGsCyzdPdmXFioahJgRJr_87sZQ&callback=initMap">
            </script>


            
        </div>
    </div>
    
    <!-- Entreprise à proximité -->
    <h3>A proximité...</h3>
    <div class="row">
        <% for company in @company.nearbys(2).limit(3) %>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading preview">
                    <%= image_tag company.photos[0].image.url(:medium) if company.photos.length > 0 %>
                </div>
                <div class="panel-body">
                    <%= link_to company.social_reason, company %><br>
                    (à <%= (company.distance*1.6).round(2) %> km)
                </div>
            </div>
        </div>
        <% end %>
    </div>